# Generated by Django 5.2.8 on 2025-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
    ]
